# Generated by Django 5.1.4 on 2025-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=500)),
                ("logintude", models.CharField(max_length=100)),
                ("weather_description", models.CharField(max_length=100)),
                ("humitidy", models.CharField(max_length=100)),
                ("temperature", models.CharField(max_length=5)),
            ],
        ),
    ]
